### ISSUE TITLE
Login app - Change the basic style 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/bi-app#12]
on the demo site app
Compare with design DAM to clone about the style
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=5290%3A29850&t=jdUBSTjC1zu0f0ws-0
Remember change text for each project
![image](https://user-images.githubusercontent.com/44457418/210479733-61d83f52-57ec-4783-a8e1-1653554f6cc5.png)

**Comment by VanTrieuThanh** [comment]
not same design ![image](https://user-images.githubusercontent.com/44457418/212258641-f299ac54-5556-4a62-9974-97f244df3369.png)

**Comment by VanTrieuThanh** [comment]
padding top 16px 
![image](https://user-images.githubusercontent.com/44457418/212259534-af353787-85b2-4be3-93ef-40b7ce46cd6a.png)
padding top 24px
![image](https://user-images.githubusercontent.com/44457418/212259635-77e081ed-d689-4f0a-8451-71a8ac82e524.png)
bold text 
![image](https://user-images.githubusercontent.com/44457418/212259922-678319b2-9aeb-485b-9981-ec8e65ee0510.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/216234101-fe771d2b-db28-40cd-94f6-1af37304448e.png)
