### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/bi-app#22]
1. Login to app
2. Click on button to Collapse the menu
![image](https://user-images.githubusercontent.com/30283123/210744656-94029c7c-5b50-431d-8723-cbf060f9ff1d.png)

**Comment by huynhngocgiau** [comment]
![Image](https://user-images.githubusercontent.com/79819354/212216067-2f42072b-b5e7-4a35-9fbd-fd427dffc49b.png)
