### ISSUE TITLE
The pageview unique does not work

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/bi-app#35]
![image](https://user-images.githubusercontent.com/30283123/211261411-8bdc03bb-3807-4a10-ab16-1c165f8a0c89.png)

When I filter pageview with Unique, it does not change the value

**Comment by huynhngocgiau** [comment]
"Unique" text hasn't been update

https://user-images.githubusercontent.com/79819354/212801551-29c45ce3-a54c-436b-8cc1-777044a421b3.mp4

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/216278608-88726f05-6337-46d1-bb7b-84ef9a311118.png)
