### ISSUE TITLE
Missing filters

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/bi-app#38]
1. Go to the page https://demo.bi.aesirx.io/data-demo.analytics.aesirx.io/audience/overview
2. Filter the day from 1-Jan to 20-Jan

Actual output:
Only show days option
Expected output:
Display the entire options of filters: hours, day, week, month 
Refer GG Analytics to see how it work https://analytics.google.com/analytics/web/#/report/visitors-overview/a114758087w170690447p170466232/_u.date00=20230107&_u.date01=20230108/

**Comment by vietredweb** [comment]
It's still missing results from API to get data from hour, week, month chị @thaoredweb
