### ISSUE TITLE
Translate multi languages

### ISSUE THREAD

**Issue by vietredweb** [aesirxio/bi-app#44]

**Comment by VanTrieuThanh** [comment]
Calendar for Thai, Viet, Danmark language 
![image](https://user-images.githubusercontent.com/44457418/212273676-c209e74f-791f-428b-b3ad-54290bb41020.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/216226401-c9ae5571-a411-4631-9313-eb494171ff87.png)
![image](https://user-images.githubusercontent.com/79819354/216226450-f2d32744-fc3d-440f-9cb9-f60efb418c75.png)
![image](https://user-images.githubusercontent.com/79819354/216226487-764365ca-0338-46f8-8340-d43c6d541790.png)
