### ISSUE TITLE
Message Status - Version 2 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/bi-app#46]
![image](https://user-images.githubusercontent.com/44457418/212270824-6e4e5ef7-9141-4e18-b721-94744adef1f9.png)
Design at 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=h8aObSmTfUsu9fNt-0

**Comment by huynhngocgiau** [comment]
Error
![image](https://user-images.githubusercontent.com/79819354/216227578-703d53a9-0b59-4569-bb47-edf7013e0d8c.png)
Warning
![image](https://user-images.githubusercontent.com/79819354/216230560-55df0d09-d356-42d7-940f-3411e7609b63.png)
Successful
![image](https://user-images.githubusercontent.com/79819354/216230714-8a37dd05-8c83-46ee-b2bf-586984f176fa.png)
