### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/bi-app#56]
All languages

![image](https://user-images.githubusercontent.com/79819354/216221577-b272ef6a-3d3c-4bdd-a08c-823a464c1bba.png)

**Comment by huynhngocgiau** [comment]
Dark mode
![image](https://user-images.githubusercontent.com/79819354/216225308-1d46061b-ecfe-471d-b4df-909eeb9ceb6c.png)
![image](https://user-images.githubusercontent.com/79819354/216225391-5906b6dc-d6d7-42df-8107-3ba8560659d7.png)

**Comment by huynhngocgiau** [comment]
Darkmode - Login 
![image](https://user-images.githubusercontent.com/79819354/216227421-77a35de4-1c48-484f-938f-f3975a1c10b9.png)

**Comment by TrucNguyenx** [comment]
Link design for the darkmode time picker:
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=2%3A329&t=EBpGfpR2t4f0HDHo-1
![image](https://user-images.githubusercontent.com/118497336/216229314-b1505dd9-e1d9-4f7b-a460-21bdc37c76f4.png)
